name: Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Log in to ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 147506552856.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t wisecow:latest .

    - name: Tag Docker image
      run: docker tag wisecow:latest 147506552856.dkr.ecr.ap-south-1.amazonaws.com/wisecow_cr/wisecow:latest

    - name: Push Docker image
      run: docker push 147506552856.dkr.ecr.ap-south-1.amazonaws.com/wisecow_cr/wisecow:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubectl-version: 'v1.26.0'

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region ap-south-1 --name your-cluster-name

    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

      
